/* Generated By:JJTree: Do not edit this line. ASTassignExpressionDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTassignExpressionDef extends SimpleNode {
  public ASTassignExpressionDef(int id) {
    super(id);
  }

  public ASTassignExpressionDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cb5dc86c5c06b8b8fb045bf18292ec33 (do not edit this line) */
