/* Generated By:JJTree: Do not edit this line. ASTexpressionR.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTexpressionR extends SimpleNode {
  public ASTexpressionR(int id) {
    super(id);
  }

  public ASTexpressionR(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6e67621ffa76754fd9604a84b70c4f5d (do not edit this line) */
