/* Generated By:JJTree: Do not edit this line. ASTReturnStatementDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReturnStatementDef extends SimpleNode {
  public ASTReturnStatementDef(int id) {
    super(id);
  }

  public ASTReturnStatementDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=069c9d0b04016da4eecd8cfba7a41169 (do not edit this line) */
