/* Generated By:JJTree: Do not edit this line. ASTStatementExpressionDefRbracket.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementExpressionDefRbracket extends SimpleNode {
  public ASTStatementExpressionDefRbracket(int id) {
    super(id);
  }

  public ASTStatementExpressionDefRbracket(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=32bdb703d8f9c674a1694707fdbbf334 (do not edit this line) */
