/* Generated By:JavaCC: Do not edit this line. CLangVisitor.java Version 7.0.5 */
public interface CLangVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTsourceCodeDef node, Object data);
  public Object visit(ASTparamListDef node, Object data);
  public Object visit(ASTparamDef node, Object data);
  public Object visit(ASTfunctionDef node, Object data);
  public Object visit(ASTvarAssignDefInInit node, Object data);
  public Object visit(ASTvarAssignDef node, Object data);
  public Object visit(ASTvarDefineDef node, Object data);
  public Object visit(ASTStatementBlockDef node, Object data);
  public Object visit(ASTStatementDef node, Object data);
  public Object visit(ASTWhileStatementDef node, Object data);
  public Object visit(ASTIfStatementDef node, Object data);
  public Object visit(ASTexpressionDef node, Object data);
  public Object visit(ASTassignExpressionDef node, Object data);
  public Object visit(ASTboolExpressionDef node, Object data);
  public Object visit(ASTbinaryBoolExpressionOrDef node, Object data);
  public Object visit(ASTbinaryBoolExpressionAndDef node, Object data);
  public Object visit(ASTbinaryExpressionEqDef node, Object data);
  public Object visit(ASTbinaryBoolOperatorCompareDef node, Object data);
  public Object visit(ASTbinaryBoolExpressionCompareDef node, Object data);
  public Object visit(ASTaddExpressionDef node, Object data);
  public Object visit(ASTmulExpressionDef node, Object data);
  public Object visit(ASTunaryExpressionDef node, Object data);
  public Object visit(ASTconstExpressionDef node, Object data);
}
/* JavaCC - OriginalChecksum=4f9b784df33137f8275f24dc6b7a8168 (do not edit this line) */
